### ISSUE TITLE
Hw_4

### ISSUE THREAD

**Issue by PavelSoloviev** [MIEE-ACS/domashnee-zadanie-no4-PavelSoloviev#1]
Сделано

**Comment by d-makarenko** [comment]
**1. Вычислить сумму положительных элементов массива, расположенных до максимального элемента.**

В твоем решении вычисляется сумма элементов + сам максимальный элемент.

Второе задание:

1. Программа падает, если не ввести размер массива
2. Функция minsumm работает не совсем правильно, так как вычисляются значения сумм только диагоналей параллельных главной и находящихся выше нее. А те, что ниже нее - не проверяются.
